<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.riversoft</groupId>
  <artifactId>riversoft-product</artifactId>
  <version>1.8.1</version>
  <packaging>pom</packaging>
  <name>RiverSoft Product</name>

  <developers>
    <developer>
      <id>woden</id>
      <name>woden</name>
      <email>wodenwang@gmail.com</email>
    </developer>
    <developer>
      <id>borball</id>
      <name>borball</name>
      <email>borball@foxmail.com</email>
    </developer>
  </developers>

  <modules>
    <module>parent</module>
    <module>util</module>
    <module>magic</module>
    <module>dbtools</module>
    <module>platform</module>
    <module>api</module>
  </modules>

  <scm>
    <url>https://svn.bpmt.app/svn/riversoft/trunk</url>
    <connection>scm:svn:https://svn.bpmt.app/svn/riversoft/trunk</connection>
    <developerConnection>scm:svn:https://svn.bpmt.app/svn/riversoft/trunk</developerConnection>
  </scm>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.5.3</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>2.9</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <additionalparam>${javadoc.opts}</additionalparam>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <reportPlugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-javadoc-plugin</artifactId>
              <configuration>
                <additionalparam>${javadoc.opts}</additionalparam>
              </configuration>
            </plugin>
          </reportPlugins>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>docker-image</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
        <maven.javadoc.skip>true</maven.javadoc.skip>
      </properties>
    </profile>
    <profile>
      <id>java8-doclint-disabled</id>
      <activation>
        <jdk>[1.8,)</jdk>
      </activation>
      <properties>
        <javadoc.opts>-Xdoclint:none</javadoc.opts>
      </properties>
    </profile>
  </profiles>
</project>
