-- bpmt-lite v1.5.0 OAuth login schema
-- This fragment is appended to both full and minimal initialization SQL files.

CREATE TABLE IF NOT EXISTS `CM_THIRDPART` (
  `THIRDPART_KEY` varchar(100) NOT NULL COMMENT '外部系统业务主键',
  `THIRDPART_NAME` varchar(200) NOT NULL COMMENT '外部系统名称',
  `CLIENT_ID` varchar(100) NOT NULL COMMENT 'OAuth Client ID',
  `CLIENT_SECRET_HASH` varchar(128) NOT NULL COMMENT 'OAuth Client Secret Hash',
  `REDIRECT_URIS` longtext NOT NULL COMMENT 'OAuth 回调地址白名单',
  `HOME_URL` varchar(500) DEFAULT NULL COMMENT '第三方系统入口地址',
  `PRI_KEY` varchar(100) NOT NULL COMMENT '外部系统权限点',
  `ACTIVE_FLAG` int(11) NOT NULL DEFAULT '1' COMMENT '启用状态',
  `DESCRIPTION` varchar(500) DEFAULT NULL COMMENT '说明',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`THIRDPART_KEY`),
  UNIQUE KEY `UK_CM_THIRDPART_CLIENT_ID` (`CLIENT_ID`),
  KEY `IDX_CM_THIRDPART_PRI_KEY` (`PRI_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外部系统主数据';

CREATE TABLE IF NOT EXISTS `CM_THIRDPART_AUTH_CODE` (
  `ID` varchar(100) NOT NULL COMMENT 'ID',
  `CODE_HASH` varchar(128) NOT NULL COMMENT '授权码 Hash',
  `CLIENT_ID` varchar(100) NOT NULL COMMENT 'OAuth Client ID',
  `THIRDPART_KEY` varchar(100) NOT NULL COMMENT '外部系统业务主键',
  `USER_ID` varchar(100) NOT NULL COMMENT '用户 ID',
  `REDIRECT_URI` varchar(500) NOT NULL COMMENT 'OAuth 回调地址',
  `STATE` varchar(500) DEFAULT NULL COMMENT 'OAuth state',
  `EXPIRES_AT` datetime NOT NULL COMMENT '过期时间',
  `USED_AT` datetime DEFAULT NULL COMMENT '使用时间',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CM_THIRDPART_AUTH_CODE_HASH` (`CODE_HASH`),
  KEY `IDX_CM_THIRDPART_AUTH_CODE_CLIENT_ID` (`CLIENT_ID`),
  KEY `IDX_CM_THIRDPART_AUTH_CODE_USER_ID` (`USER_ID`),
  KEY `IDX_CM_THIRDPART_AUTH_CODE_EXPIRES_AT` (`EXPIRES_AT`),
  KEY `IDX_CM_THIRDPART_AUTH_CODE_USED_AT` (`USED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外部系统 OAuth 授权码运行数据';

CREATE TABLE IF NOT EXISTS `CM_THIRDPART_ACCESS_TOKEN` (
  `ID` varchar(100) NOT NULL COMMENT 'ID',
  `TOKEN_HASH` varchar(128) NOT NULL COMMENT 'Access Token Hash',
  `CLIENT_ID` varchar(100) NOT NULL COMMENT 'OAuth Client ID',
  `THIRDPART_KEY` varchar(100) NOT NULL COMMENT '外部系统业务主键',
  `USER_ID` varchar(100) NOT NULL COMMENT '用户 ID',
  `EXPIRES_AT` datetime NOT NULL COMMENT '过期时间',
  `REVOKED_AT` datetime DEFAULT NULL COMMENT '吊销时间',
  `LAST_USED_AT` datetime DEFAULT NULL COMMENT '最后使用时间',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CM_THIRDPART_ACCESS_TOKEN_HASH` (`TOKEN_HASH`),
  KEY `IDX_CM_THIRDPART_ACCESS_TOKEN_CLIENT_ID` (`CLIENT_ID`),
  KEY `IDX_CM_THIRDPART_ACCESS_TOKEN_USER_ID` (`USER_ID`),
  KEY `IDX_CM_THIRDPART_ACCESS_TOKEN_EXPIRES_AT` (`EXPIRES_AT`),
  KEY `IDX_CM_THIRDPART_ACCESS_TOKEN_REVOKED_AT` (`REVOKED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外部系统 OAuth Access Token 运行数据';
